// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.23.0-devel
// 	protoc        v3.11.4
// source: analytics_service.proto

package proto

import (
	reflect "reflect"
	sync "sync"

	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Request) Reset() {
	*x = Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_analytics_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_analytics_service_proto_rawDescGZIP(), []int{0}
}

type Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AverageResponseTime float64                       `protobuf:"fixed64,1,opt,name=average_response_time,json=averageResponseTime,proto3" json:"average_response_time,omitempty"`
	StatsPerRoute       []*Response_STATS_PER_ROUTE   `protobuf:"bytes,2,rep,name=stats_per_route,json=statsPerRoute,proto3" json:"stats_per_route,omitempty"`
	RequestsPerDay      []*Response_REQUESTS_PER_DAY  `protobuf:"bytes,3,rep,name=requests_per_day,json=requestsPerDay,proto3" json:"requests_per_day,omitempty"`
	RequestsPerHour     []*Response_REQUESTS_PER_HOUR `protobuf:"bytes,4,rep,name=requests_per_hour,json=requestsPerHour,proto3" json:"requests_per_hour,omitempty"`
	TotalRequests       int64                         `protobuf:"varint,5,opt,name=total_requests,json=totalRequests,proto3" json:"total_requests,omitempty"`
}

func (x *Response) Reset() {
	*x = Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_analytics_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_analytics_service_proto_rawDescGZIP(), []int{1}
}

func (x *Response) GetAverageResponseTime() float64 {
	if x != nil {
		return x.AverageResponseTime
	}
	return 0
}

func (x *Response) GetStatsPerRoute() []*Response_STATS_PER_ROUTE {
	if x != nil {
		return x.StatsPerRoute
	}
	return nil
}

func (x *Response) GetRequestsPerDay() []*Response_REQUESTS_PER_DAY {
	if x != nil {
		return x.RequestsPerDay
	}
	return nil
}

func (x *Response) GetRequestsPerHour() []*Response_REQUESTS_PER_HOUR {
	if x != nil {
		return x.RequestsPerHour
	}
	return nil
}

func (x *Response) GetTotalRequests() int64 {
	if x != nil {
		return x.TotalRequests
	}
	return 0
}

type Response_STATS_PER_ROUTE struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id               *Response_STATS_PER_ROUTE_ID `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	NumberOfRequests int64                        `protobuf:"varint,2,opt,name=number_of_requests,json=numberOfRequests,proto3" json:"number_of_requests,omitempty"`
}

func (x *Response_STATS_PER_ROUTE) Reset() {
	*x = Response_STATS_PER_ROUTE{}
	if protoimpl.UnsafeEnabled {
		mi := &file_analytics_service_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Response_STATS_PER_ROUTE) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response_STATS_PER_ROUTE) ProtoMessage() {}

func (x *Response_STATS_PER_ROUTE) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_service_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response_STATS_PER_ROUTE.ProtoReflect.Descriptor instead.
func (*Response_STATS_PER_ROUTE) Descriptor() ([]byte, []int) {
	return file_analytics_service_proto_rawDescGZIP(), []int{1, 0}
}

func (x *Response_STATS_PER_ROUTE) GetId() *Response_STATS_PER_ROUTE_ID {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *Response_STATS_PER_ROUTE) GetNumberOfRequests() int64 {
	if x != nil {
		return x.NumberOfRequests
	}
	return 0
}

type Response_REQUESTS_PER_DAY struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id               string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	NumberOfRequests int64  `protobuf:"varint,2,opt,name=number_of_requests,json=numberOfRequests,proto3" json:"number_of_requests,omitempty"`
}

func (x *Response_REQUESTS_PER_DAY) Reset() {
	*x = Response_REQUESTS_PER_DAY{}
	if protoimpl.UnsafeEnabled {
		mi := &file_analytics_service_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Response_REQUESTS_PER_DAY) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response_REQUESTS_PER_DAY) ProtoMessage() {}

func (x *Response_REQUESTS_PER_DAY) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_service_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response_REQUESTS_PER_DAY.ProtoReflect.Descriptor instead.
func (*Response_REQUESTS_PER_DAY) Descriptor() ([]byte, []int) {
	return file_analytics_service_proto_rawDescGZIP(), []int{1, 1}
}

func (x *Response_REQUESTS_PER_DAY) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Response_REQUESTS_PER_DAY) GetNumberOfRequests() int64 {
	if x != nil {
		return x.NumberOfRequests
	}
	return 0
}

type Response_REQUESTS_PER_HOUR struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id               string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	NumberOfRequests int64  `protobuf:"varint,2,opt,name=number_of_requests,json=numberOfRequests,proto3" json:"number_of_requests,omitempty"`
}

func (x *Response_REQUESTS_PER_HOUR) Reset() {
	*x = Response_REQUESTS_PER_HOUR{}
	if protoimpl.UnsafeEnabled {
		mi := &file_analytics_service_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Response_REQUESTS_PER_HOUR) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response_REQUESTS_PER_HOUR) ProtoMessage() {}

func (x *Response_REQUESTS_PER_HOUR) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_service_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response_REQUESTS_PER_HOUR.ProtoReflect.Descriptor instead.
func (*Response_REQUESTS_PER_HOUR) Descriptor() ([]byte, []int) {
	return file_analytics_service_proto_rawDescGZIP(), []int{1, 2}
}

func (x *Response_REQUESTS_PER_HOUR) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Response_REQUESTS_PER_HOUR) GetNumberOfRequests() int64 {
	if x != nil {
		return x.NumberOfRequests
	}
	return 0
}

type Response_STATS_PER_ROUTE_ID struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Method string `protobuf:"bytes,1,opt,name=method,proto3" json:"method,omitempty"`
	Url    string `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
}

func (x *Response_STATS_PER_ROUTE_ID) Reset() {
	*x = Response_STATS_PER_ROUTE_ID{}
	if protoimpl.UnsafeEnabled {
		mi := &file_analytics_service_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Response_STATS_PER_ROUTE_ID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response_STATS_PER_ROUTE_ID) ProtoMessage() {}

func (x *Response_STATS_PER_ROUTE_ID) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_service_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response_STATS_PER_ROUTE_ID.ProtoReflect.Descriptor instead.
func (*Response_STATS_PER_ROUTE_ID) Descriptor() ([]byte, []int) {
	return file_analytics_service_proto_rawDescGZIP(), []int{1, 0, 0}
}

func (x *Response_STATS_PER_ROUTE_ID) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *Response_STATS_PER_ROUTE_ID) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

var File_analytics_service_proto protoreflect.FileDescriptor

var file_analytics_service_proto_rawDesc = []byte{
	0x0a, 0x17, 0x61, 0x6e, 0x61, 0x6c, 0x79, 0x74, 0x69, 0x63, 0x73, 0x5f, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x09, 0x0a,
	0x07, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x94, 0x05, 0x0a, 0x08, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x32, 0x0a, 0x15, 0x61, 0x76, 0x65, 0x72, 0x61, 0x67, 0x65,
	0x5f, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x01, 0x52, 0x13, 0x61, 0x76, 0x65, 0x72, 0x61, 0x67, 0x65, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x47, 0x0a, 0x0f, 0x73, 0x74, 0x61,
	0x74, 0x73, 0x5f, 0x70, 0x65, 0x72, 0x5f, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x18, 0x02, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x2e, 0x53, 0x54, 0x41, 0x54, 0x53, 0x5f, 0x50, 0x45, 0x52, 0x5f, 0x52, 0x4f,
	0x55, 0x54, 0x45, 0x52, 0x0d, 0x73, 0x74, 0x61, 0x74, 0x73, 0x50, 0x65, 0x72, 0x52, 0x6f, 0x75,
	0x74, 0x65, 0x12, 0x4a, 0x0a, 0x10, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x73, 0x5f, 0x70,
	0x65, 0x72, 0x5f, 0x64, 0x61, 0x79, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x52, 0x45,
	0x51, 0x55, 0x45, 0x53, 0x54, 0x53, 0x5f, 0x50, 0x45, 0x52, 0x5f, 0x44, 0x41, 0x59, 0x52, 0x0e,
	0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x73, 0x50, 0x65, 0x72, 0x44, 0x61, 0x79, 0x12, 0x4d,
	0x0a, 0x11, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x73, 0x5f, 0x70, 0x65, 0x72, 0x5f, 0x68,
	0x6f, 0x75, 0x72, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x21, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x52, 0x45, 0x51, 0x55, 0x45,
	0x53, 0x54, 0x53, 0x5f, 0x50, 0x45, 0x52, 0x5f, 0x48, 0x4f, 0x55, 0x52, 0x52, 0x0f, 0x72, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x73, 0x50, 0x65, 0x72, 0x48, 0x6f, 0x75, 0x72, 0x12, 0x25, 0x0a,
	0x0e, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x5f, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x73, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0d, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x73, 0x1a, 0xa3, 0x01, 0x0a, 0x0f, 0x53, 0x54, 0x41, 0x54, 0x53, 0x5f, 0x50,
	0x45, 0x52, 0x5f, 0x52, 0x4f, 0x55, 0x54, 0x45, 0x12, 0x32, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x22, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x53, 0x54, 0x41, 0x54, 0x53, 0x5f, 0x50, 0x45, 0x52, 0x5f,
	0x52, 0x4f, 0x55, 0x54, 0x45, 0x2e, 0x49, 0x44, 0x52, 0x02, 0x69, 0x64, 0x12, 0x2c, 0x0a, 0x12,
	0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x5f, 0x6f, 0x66, 0x5f, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x10, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72,
	0x4f, 0x66, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x73, 0x1a, 0x2e, 0x0a, 0x02, 0x49, 0x44,
	0x12, 0x16, 0x0a, 0x06, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x6c, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x72, 0x6c, 0x1a, 0x50, 0x0a, 0x10, 0x52, 0x45,
	0x51, 0x55, 0x45, 0x53, 0x54, 0x53, 0x5f, 0x50, 0x45, 0x52, 0x5f, 0x44, 0x41, 0x59, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x2c,
	0x0a, 0x12, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x5f, 0x6f, 0x66, 0x5f, 0x72, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x10, 0x6e, 0x75, 0x6d, 0x62,
	0x65, 0x72, 0x4f, 0x66, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x73, 0x1a, 0x51, 0x0a, 0x11,
	0x52, 0x45, 0x51, 0x55, 0x45, 0x53, 0x54, 0x53, 0x5f, 0x50, 0x45, 0x52, 0x5f, 0x48, 0x4f, 0x55,
	0x52, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69,
	0x64, 0x12, 0x2c, 0x0a, 0x12, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x5f, 0x6f, 0x66, 0x5f, 0x72,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x10, 0x6e,
	0x75, 0x6d, 0x62, 0x65, 0x72, 0x4f, 0x66, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x73, 0x32,
	0x48, 0x0a, 0x09, 0x41, 0x6e, 0x61, 0x6c, 0x79, 0x74, 0x69, 0x63, 0x73, 0x12, 0x3b, 0x0a, 0x10,
	0x41, 0x6e, 0x61, 0x6c, 0x79, 0x74, 0x69, 0x63, 0x73, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x12, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x0f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_analytics_service_proto_rawDescOnce sync.Once
	file_analytics_service_proto_rawDescData = file_analytics_service_proto_rawDesc
)

func file_analytics_service_proto_rawDescGZIP() []byte {
	file_analytics_service_proto_rawDescOnce.Do(func() {
		file_analytics_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_analytics_service_proto_rawDescData)
	})
	return file_analytics_service_proto_rawDescData
}

var file_analytics_service_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_analytics_service_proto_goTypes = []interface{}{
	(*Request)(nil),                     // 0: proto.Request
	(*Response)(nil),                    // 1: proto.Response
	(*Response_STATS_PER_ROUTE)(nil),    // 2: proto.Response.STATS_PER_ROUTE
	(*Response_REQUESTS_PER_DAY)(nil),   // 3: proto.Response.REQUESTS_PER_DAY
	(*Response_REQUESTS_PER_HOUR)(nil),  // 4: proto.Response.REQUESTS_PER_HOUR
	(*Response_STATS_PER_ROUTE_ID)(nil), // 5: proto.Response.STATS_PER_ROUTE.ID
	(*empty.Empty)(nil),                 // 6: google.protobuf.Empty
}
var file_analytics_service_proto_depIdxs = []int32{
	2, // 0: proto.Response.stats_per_route:type_name -> proto.Response.STATS_PER_ROUTE
	3, // 1: proto.Response.requests_per_day:type_name -> proto.Response.REQUESTS_PER_DAY
	4, // 2: proto.Response.requests_per_hour:type_name -> proto.Response.REQUESTS_PER_HOUR
	5, // 3: proto.Response.STATS_PER_ROUTE.id:type_name -> proto.Response.STATS_PER_ROUTE.ID
	6, // 4: proto.Analytics.AnalyticsService:input_type -> google.protobuf.Empty
	1, // 5: proto.Analytics.AnalyticsService:output_type -> proto.Response
	5, // [5:6] is the sub-list for method output_type
	4, // [4:5] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_analytics_service_proto_init() }
func file_analytics_service_proto_init() {
	if File_analytics_service_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_analytics_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_analytics_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_analytics_service_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Response_STATS_PER_ROUTE); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_analytics_service_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Response_REQUESTS_PER_DAY); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_analytics_service_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Response_REQUESTS_PER_HOUR); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_analytics_service_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Response_STATS_PER_ROUTE_ID); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_analytics_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_analytics_service_proto_goTypes,
		DependencyIndexes: file_analytics_service_proto_depIdxs,
		MessageInfos:      file_analytics_service_proto_msgTypes,
	}.Build()
	File_analytics_service_proto = out.File
	file_analytics_service_proto_rawDesc = nil
	file_analytics_service_proto_goTypes = nil
	file_analytics_service_proto_depIdxs = nil
}
